### ISSUE TITLE
Error in shard.yml

### ISSUE THREAD

**Issue by paulocoghi** [naqvis/webview#2]
On a new project, after creating `shard.yml`with:

```yml
dependencies:
  webview:
    github: naqvis/webview
```

and running `shards install`, this error is returned:

```sh
Error in shard.yml: missing required attribute: name at line 4, column 1

  2.   webview:
  3.     github: naqvis/webview
     ^

Resolving dependencies
```

**Details:**
Crystal 1.2.2 [6529d725a] (2021-11-10)
Ubuntu 20.04 64bit
libwebkit2gtk-4.0-37 (which provides `webkit2gtk 2.34.1`) installed
